"""initial tables

Revision ID: d82ccfb090b9
Revises: 
Create Date: 2023-05-12 06:55:20.748474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82ccfb090b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_key'), 'users', ['user_key'], unique=True)
    op.create_table('lifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lift_key', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('training_max', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifts_id'), 'lifts', ['id'], unique=False)
    op.create_index(op.f('ix_lifts_lift_key'), 'lifts', ['lift_key'], unique=True)
    op.create_index(op.f('ix_lifts_name'), 'lifts', ['name'], unique=False)
    op.create_index(op.f('ix_lifts_user_id'), 'lifts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lifts_user_id'), table_name='lifts')
    op.drop_index(op.f('ix_lifts_name'), table_name='lifts')
    op.drop_index(op.f('ix_lifts_lift_key'), table_name='lifts')
    op.drop_index(op.f('ix_lifts_id'), table_name='lifts')
    op.drop_table('lifts')
    op.drop_index(op.f('ix_users_user_key'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
